name: Destroy Resources

on:
  workflow_dispatch:

env:
  RG-DEV: 'rg-form-recognizer-devops-dev'
  RG-QA: 'rg-form-recognizer-devops-qa'
  RG-PROD: 'rg-form-recognizer-devops-prod'
  FORM_TAG: 'frm-devops-demo-tag-${{ secrets.SUBSCRIPTION_ID}}'

jobs:

  destroy-resource-group:

    runs-on: ubuntu-latest

    steps:

      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
          enable-AzPSSession: false     

      - name: Get Form Recognizer Ids
        run: |
          echo "FORM_DEV_ID=$(az resource list -g ${{ env.RG-DEV }}  --query "[?tags.description == '${{ env.FORM_TAG }}'].[id]" -o tsv)" >> $GITHUB_ENV
          echo "FORM_QA_ID=$(az resource list -g ${{ env.RG-QA }}  --query "[?tags.description == '${{ env.FORM_TAG }}'].[id]" -o tsv)" >> $GITHUB_ENV
          echo "FORM_PROD_ID=$(az resource list -g ${{ env.RG-PROD }}  --query "[?tags.description == '${{ env.FORM_TAG }}'].[id]" -o tsv)" >> $GITHUB_ENV
  
      - name: Destroy resource group
        run: |
         az group delete -n ${{ env.RG-DEV }} --yes
         az group delete -n ${{ env.RG-QA }} --yes
         az group delete -n ${{ env.RG-PROD }} --yes

      - name: Remove soft delete form Recognizer
        run: |
           az resource delete --ids ${{ env.FORM_DEV_ID }}
           az resource delete --ids ${{ env.FORM_QA_ID }}
           az resource delete --ids ${{ env.FORM_PROD_ID }}




    