
#
# Notice: Any links, references, or attachments that contain sample scripts, code, or commands comes with the following notification.
#
# This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code,
# provided that You agree:
#
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
# (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits,
# including attorneys’ fees, that arise or result from the use or distribution of the Sample Code.
#
# Please note: None of the conditions outlined in the disclaimer above will superseded the terms and conditions contained within the Premier Customer Services Description.
#
# DEMO POC - "AS IS"

name: Destroy Resources

on:
  workflow_dispatch:

env:
  RG-DEV: 'rg-form-recognizer-devops-dev'
  RG-QA: 'rg-form-recognizer-devops-qa'
  RG-PROD: 'rg-form-recognizer-devops-prod'
  FORM_TAG: 'frm-devops-demo-tag-${{ secrets.SUBSCRIPTION_ID}}'

jobs:

  destroy-resource-group:

    runs-on: ubuntu-latest

    steps:

      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
          enable-AzPSSession: false     
  
      - name: Destroy resource group
        run: |
         if [ $(az group exists --name ${{ env.RG-DEV }}) = false ]; then
           az group delete -n ${{ env.RG-DEV }} --yes  
         fi        
         if [ $(az group exists --name ${{ env.RG-QA }}) = false ]; then
           az group delete -n ${{ env.RG-QA }} --yes  
         fi        
         if [ $(az group exists --name ${{ env.RG-PROD }}) = false ]; then
           az group delete -n ${{ env.RG-PROD }} --yes  
         fi                          

      - name: Get Form Recognizer Ids
        run: |
          echo "FORM_DEV_ID=$(az resource list -g ${{ env.RG-DEV }}  --query "[?tags.description == '${{ env.FORM_TAG }}'].[id]" -o tsv)" >> $GITHUB_ENV
          echo "FORM_QA_ID=$(az resource list -g ${{ env.RG-QA }}  --query "[?tags.description == '${{ env.FORM_TAG }}'].[id]" -o tsv)" >> $GITHUB_ENV
          echo "FORM_PROD_ID=$(az resource list -g ${{ env.RG-PROD }}  --query "[?tags.description == '${{ env.FORM_TAG }}'].[id]" -o tsv)" >> $GITHUB_ENV

      - name: Remove soft delete form Recognizer
        run: |
           az resource delete --ids ${{ env.FORM_DEV_ID }}
           az resource delete --ids ${{ env.FORM_QA_ID }}
           az resource delete --ids ${{ env.FORM_PROD_ID }}




    