
#
# Notice: Any links, references, or attachments that contain sample scripts, code, or commands comes with the following notification.
#
# This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
# THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#
# We grant You a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute the object code form of the Sample Code,
# provided that You agree:
#
# (i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
# (ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
# (iii) to indemnify, hold harmless, and defend Us and Our suppliers from and against any claims or lawsuits,
# including attorneys’ fees, that arise or result from the use or distribution of the Sample Code.
#
# Please note: None of the conditions outlined in the disclaimer above will superseded the terms and conditions contained within the Premier Customer Services Description.
#
# DEMO POC - "AS IS"

name: Create Azure Resources

on:  
  workflow_dispatch:
          
jobs:
  create-dev-environment:
    uses: hugogirard/formRecognizerDevOps/.github/workflows/create-resources.yml@main
    with:
      resourceGroupName: 'rg-form-recognizer-devops-dev'
      location: 'eastus'      
      environmentName: 'dev'      
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS  }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
      sp_identity: ${{ secrets.SP_PRINCIPAL_OBJECT_ID }}

  create-qa-environment:
    uses: hugogirard/formRecognizerDevOps/.github/workflows/create-resources.yml@main
    with:
      resourceGroupName: 'rg-form-recognizer-devops-qa'
      location: 'eastus'     
      environmentName: 'qa'      
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS  }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
      sp_identity: ${{ secrets.SP_PRINCIPAL_OBJECT_ID }}

  create-prod-environment:
    uses: hugogirard/formRecognizerDevOps/.github/workflows/create-resources.yml@main
    with:
      resourceGroupName: 'rg-form-recognizer-devops-prod'
      location: 'eastus'     
      environmentName: 'prod'      
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS  }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
      sp_identity: ${{ secrets.SP_PRINCIPAL_OBJECT_ID  }}      

  # give-vault-access-service-principal:
  #   needs: [create-dev-environment, create-qa-environment, create-prod-environment]
  #   runs-on: ubuntu-latest

  #   steps:

  #     - name: Azure Login
  #       uses: Azure/login@v1
  #       with:
  #         creds: ${{ secrets.azure_credentials }}  

  #     - name: Give SP Dev Access Vault
  #       run: az keyvault set-policy -n ${{ needs.create-dev-environment.outputs.keyVaultName }} --secret-permissions get list --spn ${{ secrets.SP_PRINCIPAL_OBJECT_ID }}

  #     - name: Give SP QA Access Vault
  #       run: az keyvault set-policy -n ${{ needs.create-qa-environment.outputs.keyVaultName }} --secret-permissions get list --spn ${{ secrets.SP_PRINCIPAL_OBJECT_ID }}

  #     - name: Give SP Prod Access Vault
  #       run: az keyvault set-policy -n ${{ needs.create-prod-environment.outputs.keyVaultName }} --secret-permissions get list --spn ${{ secrets.SP_PRINCIPAL_OBJECT_ID }}                
  
  create-deploy-azure-function:
    needs: [create-dev-environment, create-qa-environment, create-prod-environment ]
    runs-on: ubuntu-latest

    env:
      RG_NAME: 'rg-form-recognizer-devops-utility'
      LOCATION: 'eastus'      
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/function'    
      DOTNET_VERSION: '6.0.x'              

    steps:    
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}  

      - name: Create Resource Group
        run: |
          az group create -n ${{ env.RG_NAME }} -l ${{ env.LOCATION }}

      - uses: Azure/get-keyvault-secrets@v1
        id: devSecretVault
        with:
          keyvault: ${{ needs.create-dev-environment.outputs.keyvaultName }}
          secrets: 'storageCnxString, frmEndpoint, frmKey'

      - uses: Azure/get-keyvault-secrets@v1
        id: qaSecretVault
        with:
          keyvault: ${{ needs.create-qa-environment.outputs.keyvaultName }}
          secrets: 'storageCnxString, frmEndpoint, frmKey'

      - uses: Azure/get-keyvault-secrets@v1
        id: prodSecretVault
        with:
          keyvault: ${{ needs.create-prod-environment.outputs.keyvaultName }}
          secrets: 'storageCnxString, frmEndpoint, frmKey'          

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:        
          tokenPrefix: __        
          tokenSuffix: __        
          files: '["bicep/utility.parameters.json"]'
        env:
          formRecognizerDevEndpoint: ${{ steps.devSecretVault.outputs.frmEndpoint }}
          formRecognizerQAEndpoint: ${{ steps.qaSecretVault.outputs.frmEndpoint }}
          formRecognizerProdEndpoint: ${{ steps.prodSecretVault.outputs.frmEndpoint }}
          formRecognizerDevKey: ${{ steps.devSecretVault.outputs.frmKey }}
          formRecognizerQAKey: ${{ steps.qaSecretVault.outputs.frmKey }}
          formRecognizerProdKey: ${{ steps.prodSecretVault.outputs.frmKey}}
          devStorageCnxString: ${{ steps.devSecretVault.outputs.storageCnxString }}

      - name: Deploy Azure Resources
        id: armDeployment
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.subscriptionId }}
          resourceGroupName: ${{ env.RG_NAME }}
          template: ./bicep/utility.bicep
          parameters: ./bicep/utility.parameters.json

      - name: Setup DotNet 6.0.X Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: 'Building with Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd     

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1        
        with:
          app-name: ${{ steps.armDeployment.outputs.functionName }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'     
