name: Create Azure Resources

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'The location where the resources will be created'
        default: 'eastus'
        required: true

jobs:
  create-dev-environment:
    uses: hugogirard/formRecognizerDevOps/.github/workflows/create-resources.yml@main
    with:
      resourceGroupName: 'rg-form-recognizer-devops-dev'
      location: ${{ github.event.inputs.location }}
      environmentName: 'dev'
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS  }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}

  create-qa-environment:
    uses: hugogirard/formRecognizerDevOps/.github/workflows/create-resources.yml@main
    with:
      resourceGroupName: 'rg-form-recognizer-devops-qa'
      location: ${{ github.event.inputs.location }}
      environmentName: 'dev'
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS  }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}

  create-prod-environment:
    uses: hugogirard/formRecognizerDevOps/.github/workflows/create-resources.yml@main
    with:
      resourceGroupName: 'rg-form-recognizer-devops-prod'
      location: ${{ github.event.inputs.location }}
      environmentName: 'dev'
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS  }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
