# name: Migrate modelId

# on:
#   workflow_dispatch:
#     inputs:
#       modelId:
#         required: true
#         description: 'The modelId to copy from DEV to other environment'
#         type: string

# jobs:
#   validate-model-present-in-dev:

#     runs-on: ubuntu-latest

#     steps:
#       - name: validateModelExists
#         run: |
