name: Train model in DEV

on:
  workflow_dispatch:

jobs:
  train-model:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false      

      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEYVAULT_DEV_NAME }}
          secrets: 'frmEndpoint, frmKey, strCnxString'
        id: vaultSecrets

      # Upload the file in the Azure Storage
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: model
          container_name: documents
          connection_string: ${{ steps.vaultSecrets.outputs.strCnxString }}          
          sync: false       